modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "ftbtoasts"
version = "${version}"
displayName = "FTB Toasts"
authors = "FTB Team"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.ftbtoasts]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbtoasts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.ftbtoasts]]
#modId = "architectury"
#mandatory = true
#versionRange = "[5.6.22,)"
#ordering = "AFTER"
#side = "BOTH"
